server.port=8080
spring.application.name=image-resize-service
spring.jackson.serialization.fail-on-empty-beans=false
spring.mvc.format.date-time=yyyy-MM-dd'T'HH:mm:ss.SSSZ
logging.level.org.springframework=INFO
logging.level.com.example.imageservice=DEBUG